FROM registry.access.redhat.com/ubi9/python-311
WORKDIR /app/

ARG WATCHEXEC_VERSION="2.3.0"

USER root
RUN chown -R ${USER_UID}:0 /app
USER ${USER_UID}

RUN dnf install -y sshpass && \
    dnf install -y https://github.com/watchexec/watchexec/releases/download/v${WATCHEXEC_VERSION}/watchexec-${WATCHEXEC_VERSION}-x86_64-unknown-linux-gnu.rpm && \
    dnf clean all

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

ENV BASE_DIR="/app"
ENV HOST="0.0.0.0"
ENV PORT=80

COPY ./api /app/

CMD ["watchexec", "-r", "-e", "py", "--", "python", "main.py"]