= Validation Script

== Settings

Following environment variables can be set to configure validation script

* `MAX_WORKERS` - Number of the concurrent Ansible Runner processes. Default: 2.
* `HOST` - Bind socket to this host. Default: `127.0.0.1`.
* `PORT` - Bind to a socket with this port. Default: 8000.
* `LOG_LEVEL` - Set the log level. Options are `critical`, `error`, `warning`, `info`, `debug`, `trace`. Default: `info`.
* `RELOAD` - Enable auto-reload when code was changed. This option should not be used in production due to additional resources consumption. Default: False.
* `BASE_DIR` - Base directory for the `scripts_path` and `artifacts_path`. Default: Absolute path to `main.py`.
* `SCRIPTS_PATH` - Ansible Runner input directory. Default: `<base_dir>/runtime-automation`
* `ARTIFACTS_PATH` - Ansible Runner artifacts directory. Deafault: `<base_dir>/artefacts`
* `JOBS_PATH` - Validation scripts jobs data directory. Default: `<base_dir>/jobs`
* `ANSIBLE_USER` - The username for SSH connections to target hosts. Default: `lab-user`.
* `ANSIBLE_PORT` - The port number for SSH connections. Default: `22`.
* `ANSIBLE_SSH_PRIVATE_KEY_FILE` - Path to the SSH private key file for key-based authentication. If set, this method is used even if `ANSIBLE_PASSWORD` is also set.
* `ANSIBLE_PASSWORD` - The password for password-based authentication. Used only if `ANSIBLE_SSH_PRIVATE_KEY_FILE` is *not* set.

[IMPORTANT]
====
The service requires authentication configuration to start. You *must* set either `ANSIBLE_SSH_PRIVATE_KEY_FILE` or `ANSIBLE_PASSWORD`.
====

model_config = SettingsConfigDict(env_file=f'{base_dir}/.env')


== Running locally

Run the following command to start the validation script locally:
----
$ cd api
$ python3 main.py
----

[NOTE:]
====
The `.env` file can be used to set the environment variables.

Example:
----
BASE_DIR=/home/user/validation-scripts
SCRIPTS_PATH=runtime-automation
RELOAD=True
----

====


== Building and running in container

. Build container
+
----
$ podman build -t validation-script .
----

. Run
+
----
$ podman run --rm -p 8080:80 -v ./runtime-automation/:/app/runtime-automation:ro,Z validation-script
----
