= Validation Script

== Endpoints

=== Run Task

*Method:* `POST`
*Path:* `/api/{module}/{stage}`

This endpoint creates and schedules a new job to run a task.

*Parameters:*

*   `module` (path): The name of the module to run.
*   `stage` (path): The stage of the module to run.

*Example Request:*

`POST /api/module-02/setup`

*Response:*

```json
{
  "Job_id": "a1b2c3d4-e5f6-7788-9900-aabbccddeeff"
}
```

*Response Codes:*

*   `202 Accepted`: The job was successfully created and scheduled.
*   `404 Not Found`: The module or stage was not found.
*   `500 Internal Server Error`: Failed to create the job.

=== Get Job Status

*Method:* `GET`
*Path:* `/api/job/{uid}`

This endpoint retrieves the status of a job.

*Parameters:*

*   `uid` (path): The UUID of the job.

*Example Request:*

`GET /api/job/a1b2c3d4-e5f6-7788-9900-aabbccddeeff`

*Response:*

```json
{
  "Status": "successful"
}
```

*Response Codes:*

*   `200 OK`: The job status was successfully retrieved.
*   `404 Not Found`: The job was not found.

=== Get Module Config

*Method:* `GET`
*Path:* `/api/config`

This endpoint retrieves the module configuration.

*Example Request:*

`GET /api/config`

*Response:*

```yaml
module-02:
  - setup
  - solve
  - validation
```

*Response Codes:*

*   `200 OK`: The module configuration was successfully retrieved.

== Settings

Following environment variables can be set to configure validation script

* `MAX_WORKERS` - Number of the concurrent Ansible Runner processes. Default: 2.
* `HOST` - Bind socket to this host. Default: `127.0.0.1`.
* `PORT` - Bind to a socket with this port. Default: 8000.
* `LOG_LEVEL` - Set the log level. Options are `critical`, `error`, `warning`, `info`, `debug`, `trace`. Default: `info`.
* `RELOAD` - Enable auto-reload when code was changed. This option should not be used in production due to additional resources consumption. Default: False.
* `BASE_DIR` - Base directory for the `scripts_path` and `artifacts_path`. Default: Absolute path to `main.py`.
* `SCRIPTS_PATH` - Ansible Runner input directory. Default: `<base_dir>/runtime-automation`
* `ARTIFACTS_PATH` - Ansible Runner artifacts directory. Deafault: `<base_dir>/artefacts`
* `JOBS_PATH` - Validation scripts jobs data directory. Default: `<base_dir>/jobs`
* `ANSIBLE_USER` - The username for SSH connections to target hosts. Default: `lab-user`.
* `ANSIBLE_PORT` - The port number for SSH connections. Default: `22`.
* `ANSIBLE_SSH_PRIVATE_KEY_FILE` - Path to the SSH private key file for key-based authentication. If set, this method is used even if `ANSIBLE_PASSWORD` is also set.
* `ANSIBLE_PASSWORD` - The password for password-based authentication. Used only if `ANSIBLE_SSH_PRIVATE_KEY_FILE` is *not* set.
* `DEBUG` - Enable debug mode. This will print more detailed logs and output. Default: False.

[IMPORTANT]
====
The service requires authentication configuration to start. You *must* set either `ANSIBLE_SSH_PRIVATE_KEY_FILE` or `ANSIBLE_PASSWORD`.
====

== Running locally

Run the following command to start the validation script locally:
----
$ cd api
$ python3 main.py
----

[NOTE:]
====
The `.env` file can be used to set the environment variables.

Example:
----
BASE_DIR=/home/user/validation-scripts
SCRIPTS_PATH=runtime-automation
RELOAD=True
----

====


== Building and running in container

. Build container
+
----
$ podman build -t validation-script .
----

. Run
+
----
$ podman run --rm -p 8080:80 -v ./runtime-automation/:/app/runtime-automation:ro,Z validation-script
----
