---
- name: Playbook for executing multiple validation scripts via ansible-runner API
  hosts: localhost # Run the main logic on localhost to control the loop
  gather_facts: false
  become: false

  tasks:
    - name: Ensure script_executions variable is defined
      ansible.builtin.assert:
        that:
          - script_executions is defined
          - script_executions is iterable
        fail_msg: "Variable 'script_executions' must be defined as a list."
      run_once: true # Only need to check this once

    - name: Execute each script defined in script_executions
      include_tasks: playbook_single_run.yml # Use include_tasks for better structure
      loop: "{{ script_executions }}"
      loop_control:
        loop_var: script_item # Define the loop variable name
      register: r_included_task_results